GitDepend/CommandLine/UpdateSubOptions.cs
GitDepend/Commands/UpdateCommand.cs
GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs
GitDepend/Visitors/DependencyVisitorAlgorithm.cs

Why: The update command needs to be able to target a specific
dependency, or multiple dependencies.
* restricting the visitdependency and visitproject endpoints to the
specified dependencies.

issue #84 The update can target specified deps

---

docs/source/usage/update.rst

Why:
* No documentation currently exists.
* Creating a documentation page and adding some instructions

issue #125 Adding documentation for update

---

docs/source/usage.rst
docs/source/usage/config.rst

Why:
* No documentation currently exists
* Creating a documentation page and adding some instructions

issue #120 Adding documentation for config

---

docs/source/usage.rst
docs/source/usage/clone.rst
docs/source/usage/update.rst

Why:
* No documentation currently exists
* Adding a usage/clone.rst file with basic help

issue #119 Adds documentation for the clone verb

---

docs/source/usage.rst
docs/source/usage/sync.rst

Why:
* No documentation exists.
* Creating documentation

#124 Adding documentation for sync

---

docs/source/usage.rst

Why:
* Out of order links might be harder to find
* Re-ordering the links on the usage page.

issue #141 Updated documentation with better order

---

GitDepend.UnitTests/Properties/AssemblyInfo.cs
GitDepend/Properties/AssemblyInfo.cs
Makefile
make.bat

Why:
* I would like a way to quickly install the latest chocolatey package
* Adds an install target in the Makefile that depends on package-debug that will install the latest chocolatey package.

issue #143 adds make install as a target

---

GitDepend.UnitTests/Visitors/DisplayStatusVisitorTests.cs

Why:
* There were no unit tests that caught #138
* Adding a unit test that verifies the working directory for the git
operation while doing a status check

issue #138 Adds a unit test for incorrect status

---

GitDepend.Commandline.nuspec
GitDepend.Portable.nuspec
README.md
docs/source/usage_example.rst

Why:
* GitDepend was recently moved to the GitDepend organization. Several links now need to be updated to reflect this change.
* Updating the links in the nuspec files.

issue #149 update urls in nuspec files

---

GitDepend.UnitTests/Visitors/BuildAndUpdateDependenciesVisitorTests.cs
GitDepend/Busi/Nuget.cs
GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs

Why:
* arguments wrapped in quotes were incorrectly handled
* uses a more intelligent parsing routine to group arguments wrapped in
quotes.
* Also addresses #162 (commit message should specify which solution was
updated)

issue #161 fixes the arguments parsing for nuget

---

GitDepend/Busi/Nuget.cs
GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs

Why:
* Update doesn't fail when nuget fails to update a package
* Adding code to detect whether warnings are being thrown for being
unable to update

issue #169 Update now returns FailedToRunNugetCommand

---

GitDepend/Busi/DependencyExtensions.cs
GitDepend/Commands/BranchCommand.cs
GitDepend/Commands/CloneCommand.cs
GitDepend/Commands/NamedDependenciesCommand.cs
GitDepend/Commands/SyncCommand.cs
GitDepend/Commands/UpdateCommand.cs
GitDepend/Resources/strings.Designer.cs
GitDepend/Resources/strings.resx
GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs
GitDepend/Visitors/CheckOutDependencyBranchVisitor.cs
GitDepend/Visitors/CreateBranchVisitor.cs
GitDepend/Visitors/DependencyVisitorAlgorithm.cs
GitDepend/Visitors/ListAllBranchesVisitor.cs
GitDepend/Visitors/ListMergedBranchesVisitor.cs
GitDepend/Visitors/NamedDependenciesVisitor.cs
GitDepend/Visitors/VerifyCorrectBranchVisitor.cs

Right now we have all the outputs that we've created to be grabbing from the Resx file.
We don't have a way of showing the HelpText out of the `Option` attribute due to the fact the strings are not a const.
Maybe that's a separate issue we could bring out later and see if there's a way around this.

#177 moved console strings to resx strings file

---

GitDepend.UnitTests/Commands/InitCommandTests.cs
GitDepend.UnitTests/Configuration/BuildTests.cs
GitDepend.UnitTests/Configuration/GitDependFileTests.cs
GitDepend/Commands/InitCommand.cs
GitDepend/Configuration/Build.cs

Why:
* The init verb was not asking for the name
* Asking for the name in the InitCommand

issue #167 init now asks for the name

---

CONTRIBUTING.md
GitDepend.IntegrationTests/GitDepend.IntegrationTests.csproj
GitDepend.IntegrationTests/GitDepend.IntegrationTests.v2.ncrunchproject
GitDepend.IntegrationTests/GitDependExecutionInfo.cs
GitDepend.IntegrationTests/Properties/AssemblyInfo.cs
GitDepend.IntegrationTests/Scenarios/HelpPageScenario.cs
GitDepend.IntegrationTests/TestFixtureBase.cs
GitDepend.IntegrationTests/packages.config
GitDepend.UnitTests/Commands/UpdateCommandTests.cs
GitDepend.UnitTests/Visitors/CheckArtifactsVisitorTests.cs
GitDepend.sln
GitDepend/CommandLine/UpdateSubOptions.cs
GitDepend/Commands/CommandParser.cs
GitDepend/Commands/UpdateCommand.cs
GitDepend/Visitors/CheckArtifactsVisitor.cs

Why:
* we need at least some basic integration tests
* Adding a new project to house integration tests.

issue #181 IntegrationTests framework

---

GitDepend/Commands/UpdateCommand.cs
GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs
GitDepend/Visitors/CheckArtifactsVisitor.cs

Why:
* GitDepend update was not properly updating the named dependency.
* Marking projects as need to update if any of it's libraries were updated.

issue #170  fixes update <name>

---

GitDepend/Commands/InitCommand.cs

Why:
* dep init was waiting for user input for build args, but never asking
the user for arguments. This was confusing for users.
* Displaying a message asking for build arguments before waiting for
user input.

issue #203 dep init now asks for build args

---

GitDepend.UnitTests/Visitors/DependencyVisitorAlgorithmTests.cs
GitDepend/Visitors/DependencyVisitorAlgorithm.cs

Why:
* The clean install was not loading the configuration, because before
the clone, the file didn't exist.
* Loading the configuration into the dependency.

issue #211 Update command now works on a clean install

---

GitDepend.UnitTests/Visitors/CheckOutBranchVisitorTests.cs
GitDepend/Visitors/CheckOutBranchVisitor.cs

encountered
Why:
* Currently if you checkout a branch that already exists on any
dependency then the command will fail.
* Fixing the visitor to not fail when there are errors encountered.

issue #209 Checkout, create new branch will keep processing if error

---

GitDepend.UnitTests/Visitors/DeleteBranchVisitorTests.cs
GitDepend/Visitors/DeleteBranchVisitor.cs

Why:
* Currently if it encounters an error it will not continue processing
the rest of the dependencies.
* If it encounters an error, the visitor will return success to continue
processing
* Fixed the unit test that was checking for an error return code

issue #207 Forceful delete will traverse dependencies

---

GitDepend.UnitTests/Visitors/CreateBranchVisitorTests.cs
GitDepend/Visitors/CreateBranchVisitor.cs

encountering error.
Why:
* The branch command should continue through all dependencies when
creating a branch
* Fixing the unit test by expecting success when branch creation fails.
* Updating the visitor to check if it failed to run the git command. If
so, then it returns success to continue processing the rest of the
dependencies

issue #199 Updating branch command to traverse through dependencies when

---

GitDepend.UnitTests/Commands/CommandParserTests.cs
GitDepend/CommandLine/ManageSubOptions.cs
docs/source/usage/manage.rst

Why:
* Currently named dependencies are not required as an argument to the
manage command
* Requiring the manage command to have the name.

issue #215 Adding required to name on manage command

---

GitDepend.UnitTests/Commands/CommandParserTests.cs
GitDepend.UnitTests/Commands/PullCommandTests.cs
GitDepend.UnitTests/GitDepend.UnitTests.csproj
GitDepend.UnitTests/Visitors/PullBranchVisitorTests.cs
GitDepend/Busi/Git.cs
GitDepend/Busi/IGit.cs
GitDepend/CommandLine/Options.cs
GitDepend/CommandLine/PullSubOptions.cs
GitDepend/Commands/CommandParser.cs
GitDepend/Commands/PullCommand.cs
GitDepend/GitDepend.csproj
GitDepend/Visitors/PullBranchVisitor.cs
docs/source/usage.rst
docs/source/usage/pull.rst

issue #186 Adding a pull verb to the list of commands
Why:
* Currently we don't have support for pulling from named or all
dependencies
* Adding tests for the new code
* Adding a new visitor to perform the pull operation
* Adding a new command

issue #186 Adding a pull verb to the list of commands

---

GitDepend.UnitTests/Busi/ReturnCodeExtensionsTests.cs
GitDepend.UnitTests/GitDepend.UnitTests.csproj
GitDepend/Commands/ManageCommand.cs
GitDepend/Resources/strings.Designer.cs
GitDepend/Resources/strings.resx
GitDepend/ReturnCode.cs

Why:
* The code being returned was not correct.
* Added unit tests to make sure the correct return code and key were
matching up.
* Fixing the order of the enumeration

issue #222 Manage command now returns correct code

---

GitDepend/Commands/StatusCommand.cs
GitDepend/Visitors/DisplayStatusVisitor.cs

issue #226
Why:
* Currently only fetch was being done on the calling project directory
* Adding a fetch when going through the dependencies

Performing fetch on each dependency's directory

---

GitDepend/Commands/ListCommand.cs
GitDepend/Resources/strings.Designer.cs
GitDepend/Resources/strings.resx

Why:
* When list couldn't find a name it would print out a blank name. It
looked odd
* Printing a message letting them know it couldn't be found

issue #227 List will now print out a message as opposed to nothing

---

GitDepend.UnitTests/Visitors/BuildAndUpdateDependenciesVisitorTests.cs
GitDepend/Resources/strings.Designer.cs
GitDepend/Resources/strings.resx
GitDepend/ReturnCode.cs
GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs

We are now making sure that the build script exists, so it doesn't
crash.
issue #231
Why:
* If there would not be a build script it would throw an error
* Adding a check to make sure the build script exists.
* Fixing the unit tests that were using the visitor affected

We are now making sure that the build script exists, so it doesn't crash.
