GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs
=> Moves the cache folder to ApplicationData

README.md
=> Adds a badge for the appveyor build status

README.md
=> Adds badges for the chocolatey package

GitDepend/CommandLine/CloneSubOptions.cs, GitDepend/CommandLine/CommonSubOptions.cs, GitDepend/CommandLine/ConfigSubOptions.cs, GitDepend/CommandLine/InitSubOptions.cs, GitDepend/CommandLine/UpdateSubOptions.cs, GitDepend/Commands/CloneCommand.cs, GitDepend/Commands/CommandParser.cs, GitDepend/Commands/ICommand.cs, GitDepend/Commands/UpdateCommand.cs, GitDepend/Configuration/Build.cs, GitDepend/Configuration/Dependency.cs, GitDepend/Configuration/GitDependFile.cs, GitDepend/Configuration/Packages.cs, GitDepend/Git.cs, GitDepend/GitDepend.csproj, GitDepend/Nuget.cs, GitDepend/ReturnCodes.cs, GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs, GitDepend/Visitors/CheckOutBranchVisitor.cs, GitDepend/Visitors/DependencyVisitorAlgorithm.cs, GitDepend/Visitors/IVisitor.cs
closes #55 
All warnings are now considered errors, including the failure to include xml comments on public classes.
=> Enforces xml comments

APACHE_LICENSE, GitDepend.UnitTests/GitDepend.UnitTests.csproj, GitDepend.UnitTests/MockingUnityContainer.cs, GitDepend.UnitTests/MockingUnityContainerExtension.cs, GitDepend.UnitTests/MockingUnityContainerExtensions.cs, GitDepend.UnitTests/TestFixtureBase.cs, GitDepend.UnitTests/Visitors/BuildAndUpdateDependenciesVisitorTests.cs, GitDepend.UnitTests/Visitors/CheckOutBranchVisitorTests.cs, GitDepend.UnitTests/Visitors/DependencyVisitorAlgorithmTests.cs, GitDepend.UnitTests/app.config, GitDepend.UnitTests/packages.config, GitDepend/Busi/Git.cs, GitDepend/Busi/GitDependFileFactory.cs, GitDepend/Busi/IGit.cs, GitDepend/Busi/INuget.cs, GitDepend/Busi/Nuget.cs, GitDepend/Commands/CloneCommand.cs, GitDepend/Commands/CommandParser.cs, GitDepend/Commands/InitCommand.cs, GitDepend/Commands/ShowConfigCommand.cs, GitDepend/Commands/UpdateCommand.cs, GitDepend/DependencyInjection.cs, GitDepend/GitDepend.csproj, GitDepend/Program.cs, GitDepend/UnityConfig.cs, GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs, GitDepend/Visitors/CheckOutBranchVisitor.cs, GitDepend/Visitors/DependencyVisitorAlgorithm.cs, GitDepend/packages.config
Hooks up Unity
Unity extensions for using JustMock and Unity together were copied over from Telerik.JustMock.Unity
=> closes #62

CONTRIBUTING.md
=> Feature/#43 contributing.md

appveyor.yml
Only release/* branches will push automatically
=> The develop branch no longer automatically publishes alpha packages

docs/source/choco_install.rst, docs/source/index.rst, docs/source/nuget_install.rst, docs/source/why.rst
=> Fixes the home page of the documentation

GitDepend/Busi/GitDependFileFactory.cs, GitDepend/Program.cs, GitDepend/UnityConfig.cs, README.md
=> Fixes a null reference exception

chocolateyInstall.ps1, chocolateyUninstall.ps1
=> chocolatey now registers dep instead of gdep

GitDepend.UnitTests/Commands/CommandParserTests.cs, GitDepend.UnitTests/Commands/ShowConfigCommandTests.cs, GitDepend.UnitTests/Commands/StatusCommandTests.cs, GitDepend.UnitTests/GitDepend.UnitTests.csproj, GitDepend.UnitTests/Visitors/DisplayStatusVisitorTests.cs, GitDepend/Busi/ConsoleWrapper.cs, GitDepend/Busi/IConsole.cs, GitDepend/CommandLine/CommonSubOptions.cs, GitDepend/CommandLine/NamedDependenciesOptions.cs, GitDepend/CommandLine/Options.cs, GitDepend/CommandLine/StatusSubOptions.cs, GitDepend/Commands/CommandParser.cs, GitDepend/Commands/ConfigCommand.cs, GitDepend/Commands/StatusCommand.cs, GitDepend/GitDepend.csproj, GitDepend/Program.cs, GitDepend/ReturnCode.cs, GitDepend/Visitors/DisplayStatusVisitor.cs, docs/source/usage.rst
fixes #83 
The status verb shows the git status on all dependencies.
=> Initial implementation of the status verb

GitDepend.UnitTests/Commands/CommandParserTests.cs, GitDepend.UnitTests/Commands/ListCommandTests.cs, GitDepend.UnitTests/Configuration/DependencyTests.cs, GitDepend.UnitTests/Configuration/GitDependFileTests.cs, GitDepend.UnitTests/GitDepend.UnitTests.csproj, GitDepend.UnitTests/TestFixtureBase.cs, GitDepend.UnitTests/Visitors/DependencyVisitorAlgorithmTests.cs, GitDepend.UnitTests/Visitors/DisplayStatusVisitorTests.cs, GitDepend/CommandLine/ListSubOptons.cs, GitDepend/CommandLine/Options.cs, GitDepend/Commands/CloneCommand.cs, GitDepend/Commands/CommandParser.cs, GitDepend/Commands/ListCommand.cs, GitDepend/Configuration/Dependency.cs, GitDepend/Configuration/GitDependFile.cs, GitDepend/GitDepend.csproj, GitDepend/Visitors/CheckOutBranchVisitor.cs, GitDepend/Visitors/DependencyVisitorAlgorithm.cs, GitDepend/Visitors/DisplayStatusVisitor.cs, docs/source/usage_example.rst
=> Implements the list verb

GitDepend.UnitTests/Commands/UpdateCommandTests.cs, GitDepend.UnitTests/FakeProcess.cs, GitDepend/Busi/IProcess.cs, GitDepend/Busi/Nuget.cs, GitDepend/Busi/ProcessWrapper.cs, GitDepend/Commands/UpdateCommand.cs, GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs
=> #90 Displays a summary page after updating dependencies.

GitDepend.UnitTests/Busi/GitTests.cs, GitDepend/Busi/Git.cs, GitDepend/Visitors/BuildAndUpdateDependenciesVisitor.cs
=> Improves the commit message when updating dependencies.

GitDepend.UnitTests/Busi/GitTests.cs, GitDepend.UnitTests/Commands/CheckOutCommandTests.cs, GitDepend.UnitTests/Commands/UpdateCommandTests.cs, GitDepend.UnitTests/GitDepend.UnitTests.csproj, GitDepend.UnitTests/Visitors/CheckOutBranchVisitorTests.cs, GitDepend.UnitTests/Visitors/CheckOutDependencyBranchVisitorTests.cs, GitDepend/Busi/Git.cs, GitDepend/Busi/IGit.cs, GitDepend/CommandLine/CheckOutSubOptions.cs, GitDepend/CommandLine/Options.cs, GitDepend/Commands/BranchCommand.cs, GitDepend/Commands/CheckOutCommand.cs, GitDepend/Commands/CloneCommand.cs, GitDepend/Commands/UpdateCommand.cs, GitDepend/GitDepend.csproj, GitDepend/Visitors/CheckOutDependencyBranchVisitor.cs
Implements the following git commands
* git checkout <branch_name>
* git checkout -b <branch_name>
=> issue #105 Implements the checkout verb

GitDepend.UnitTests/Commands/CommandParserTests.cs, GitDepend/Commands/BranchCommand.cs, GitDepend/Commands/CheckOutCommand.cs, GitDepend/Commands/CommandParser.cs
=> issue #88 branches sync to config after checkout

docs/source/usage.rst, docs/source/usage/checkout.rst
=> issue #118 adds checkout docs

docs/source/usage.rst, docs/source/usage/init.rst
Why:
* No documentation exists
* Adding basic documentation
=> issue #121 Adds documentation for init

README.md, docs/source/usage.rst, docs/source/usage/list.rst
Why:
* No documentation currently exists
* Adding usage/list.rst with basic documentation
=> issue #122 Adds documentation for the list verb

docs/source/usage.rst
Why:
* Out of order links might be harder to find
* Re-ordering the links on the usage page.
=> issue #141 Updated documentation with better order

GitDepend.UnitTests/Commands/UpdateCommandTests.cs, GitDepend.UnitTests/GitDepend.UnitTests.csproj, GitDepend.UnitTests/Visitors/CheckArtifactsVisitorTests.cs, GitDepend/Commands/UpdateCommand.cs, GitDepend/Configuration/NugetPackageReference.cs, GitDepend/GitDepend.csproj, GitDepend/Resources/strings.Designer.cs, GitDepend/Resources/strings.resx, GitDepend/ReturnCode.cs, GitDepend/Visitors/CheckArtifactsVisitor.cs
This takes care of issue #171 
*Added a new visitor, which will check the artifacts of the project and the dependencies to make sure they are all up to date.
*Added unit tests to verify the visitor works as designed.
* Updated current unit tests so they will still pass.
=> Checking Artifacts - takes care of issue #171

GitDepend.UnitTests/Commands/UpdateCommandTests.cs, GitDepend.UnitTests/Visitors/CheckArtifactsVisitorTests.cs, GitDepend/Resources/strings.Designer.cs, GitDepend/Resources/strings.resx, GitDepend/Visitors/CheckArtifactsVisitor.cs
Fixing the failing unit test in @pdubb29 pr to fix #180
=> Fixes unit tests in pdubb29 pr for #180

GitDepend.UnitTests/Busi/GitTests.cs, GitDepend/Busi/Git.cs, GitDepend/Busi/IGit.cs, GitDepend/Commands/StatusCommand.cs, Makefile
Why:
* status could make you think that you were up to date when in fact you were not.
* adding a fetch before status.
=> issue #187 fetches before displaying status
